pages:
  # key is the dirname of pages in src/pages
  home:
    # 首页配置
    zh-cn:
      title: 'Go-Spring 首页'
      keywords: '关键词1，关键词2'
      description: '页面内容简介'
    # home config
    en-us:
      title: 'Go-Spring Home'
      keywords: 'keyword1,keyword2'
      description: 'page description'
  blog:
    # 博客列表页配置
    zh-cn:
      title: 'Go-Spring 博客'
      keywords: '关键词1，关键词2'
      description: '页面内容简介'
    en-us:
      # blog list page config
      title: 'Go-Spring Blog'
      keywords: 'keyword1,keyword2'
      description: 'page description'